### ISSUE TITLE
After editing my account, it kept loading and can't save again

### ISSUE THREAD

**Issue by anniejingchen** [clowdr-app/clowdr-web-app#104]
Issue: When I tried to edit and save my Account. The content has been updated in the db. But it just kept loading and I have to refresh the web-page to stop it.
![image](https://user-images.githubusercontent.com/51510527/89484107-95477600-d752-11ea-9c99-3af1279c8fcf.png)
It displayed this error below
![image](https://user-images.githubusercontent.com/51510527/89483900-0a667b80-d752-11ea-8b40-d3f955d1732f.png)
The log in the backend is below. It shows "Cannot find module 'moment-timezone' for cloud func program.js".
![image](https://user-images.githubusercontent.com/51510527/89483715-9330e780-d751-11ea-92e0-45a4c1b62642.png)

**Comment by jon-bell** [comment]
You may need to do `npm install` in the `backend/cloud` directory, and then re-deploy the backend to Back4App (I would suggest that you use their command line `b4a deploy` tool). This is working fine on my backend.

**Comment by anniejingchen** [comment]
Thank you Jon. I will try it. So far I only updated the backend cloud functions.

**Comment by bcpierce00** [comment]
If this issue has not been observed in the deployed Clowdr, then maybe it should be deleted?  Jing, are you still having problems?

**Comment by jon-bell** [comment]
This was 100% a result of not typing `npm install`
