### ISSUE TITLE
"Program at a Glance" Nits

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#115]
- [x] The "Upcoming Events" display in the left sidebar should list only the _immediately_ upcoming event in each track. (It's too long, otherwise, so you can't keep it up all the time).  
- [x] A small display weirdness: If my sidebar looks like this
<img width="248" alt="image" src="https://user-images.githubusercontent.com/7014411/89898632-081b7b80-dbaf-11ea-99dc-bf3ef216373a.png">
and click on Announcements to bring up the chat window, the list of upcoming events gets reordered on the screen!

**Comment by jon-bell** [comment]
I am working on this. It is unfortunately not "easy/small" because it is a component of the refactoring that we discussed yesterday to schedule each program item - this is somewhat significant, but I will get it done by ICFP.

**Comment by jon-bell** [comment]
now fixed in master.
