### ISSUE TITLE
Admin / Registrations page is confusing

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#116]
* [ ] It's not clear what the list of uploaded files in the upper left is for, or what the consequences are of deleting one
![image](https://user-images.githubusercontent.com/7014411/89942274-45e9c580-dbea-11ea-9c02-c7ae79dce794.png)
* [ ] Not clear what "current filter" means, or how to change it
![image](https://user-images.githubusercontent.com/7014411/89942367-6d409280-dbea-11ea-813f-5dbb15733fd5.png)
* [ ] Not clear what "Latest since" means
![image](https://user-images.githubusercontent.com/7014411/89942412-847f8000-dbea-11ea-8a18-8e84ed73bec1.png)
* [ ] "Upload File" button should be blue

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
