### ISSUE TITLE
Recursive Display when Zoom sessions ended by hosts

### ISSUE THREAD

**Issue by pained** [clowdr-app/clowdr-web-app#118]
While testing for CSCW2020 I joined a Zoom room via the browser embedded option in the latest version of Chrome (84.0.4147.125 (Official Build) (64-bit)). As host from my Zoom app I ended the room/session and the browser embedded instance displayed a message to this effect (the host has ended the meeting). Once I clicked okay the UI recursively displayed the overall Clowdr page within this frame rather than an empty space or some other message.

![](https://user-images.githubusercontent.com/254765/90062200-2b702480-dc9c-11ea-97a8-6185783cecc5.png)

**Comment by crista** [comment]
I have a repro.

**Comment by jon-bell** [comment]
It's the `leaveUrl` part of the zoom webSDK, we just need to make an HTML page somewhere that says "Your meeting is over" and give that URL instead - https://marketplace.zoom.us/docs/sdk/native-sdks/web/getting-started/integrate

**Comment by EdNutting** [comment]
Would it be better to detect the meeting has ended and so have the page re-render, replacing the iFrame with a message? Rather than directing the iFrame to a new page. (iFrames are poison and a nightmare - can we avoid them entirely somehow?!)

**Comment by jon-bell** [comment]
Yes, that would be even better!

Unfortunately we need to stick with the iframe unless we drop Zoom. Zoom’s WebSDK is built in react, but they won’t distribute it as react components, and it needs to be able to fully own the DOM :/

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
