### ISSUE TITLE
Can't start video source to join clowdr room

### ISSUE THREAD

**Issue by lemonidas** [clowdr-app/clowdr-web-app#119]
While playing for the demo session,  I couldn't join a breakout room with the warning/error:

Warning: Call to getUserMedia failed: DOMException: Could not start video source
Error: Uncaught (in promise) DOMException: Could not start video source

Using Windows/Chrome.

![image](https://user-images.githubusercontent.com/873654/90064081-3f298400-dcb8-11ea-928a-44c291f9594b.png)

**Comment by jon-bell** [comment]
This is a known issue that will occur if you do not have a camera, or if you do not click "Allow access to my camera and microphone." You can reset those permissions here - https://blog.scener.com/permissions/ . We'll add documentation to this effect on that page.

**Comment by bcpierce00** [comment]
@lemonidas Please let us know if this reset procedure does the trick for you...

**Comment by lemonidas** [comment]
I just checked and it did. It was weird because the settings did show allowed access to the camera and microphone, but resetting the settings caused the prompt to reappear and it worked.

**Comment by bcpierce00** [comment]
Next question: Is there someplace in the UI that we could give people the same information we gave you, in case they are in the same situation?  E.g., maybe below the “connecting” message?  (If there is a way to make the help message show up only after four or five seconds, that might avoid distracting people that don't need it.)

**Comment by lemonidas** [comment]
Make it the alt-text of that component? I know I instinctively hovered over it just in case. Alternatively, maybe we could use the notification mechanism for that? But then it should only show the notification if this exception is raised I guess.

**Comment by jon-bell** [comment]
<img width="1352" alt="Screen Shot 2020-08-13 at 10 11 31 AM" src="https://user-images.githubusercontent.com/2130186/90144940-6ed69b80-dd4d-11ea-858a-ae9bfabff704.png">
I added this error handler
