### ISSUE TITLE
Rethink how breakout rooms are presented in the UI

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr-web-app#121]
![](https://user-images.githubusercontent.com/506426/90082401-b0c7f900-dcdd-11ea-9774-894e79c7be4e.png)

The "Breakout Room" is confusing and many participants may join it by accident, instead of the Ongoing chat.
Suggestion - make the 'Breakout Room' a link and add a button to the ongoing chat. Example [incomplete]:
![](https://user-images.githubusercontent.com/506426/90082551-0e5c4580-dcde-11ea-8b08-2cf2402f77dc.png)

**Comment by jon-bell** [comment]
This is a great suggestion. I agree that “breakout room” is confusing terminology but I’m not sure that permanent/ongoing discussion is perfect either. The key power of the UI being in clowdr and not zoom or slack is that we know all about the program and can leverage that context, so we should. 

What about: if there is a “live” (recorded talk) presentation happening now, we add a prominent button that says “join talk session” and if there is a Q&A happening now we add a prominent button that says “join Q&A session”? And, if they are not happening now you just get the current view (that says when each session will be). Not sure what to call the “breakout room” though.

**Comment by bcpierce00** [comment]
This sounds great.  

Hanneli had a somewhat brutal quick fix for the "what to call the breakout room" problem: Just delete it!  (-: but also semi-serious: I agree with her that the multiplicity of rooms with overlapping purposes is more confusing than helpful right now, and that may require more design effort to really fix than we have time for)

**Comment by jon-bell** [comment]
That’s easily done - it’s a flag on each track. I will remove the text that shows up otherwise and says “No breakout room” (so it just says nothing - that way if there are posters or something that it makes sense for you can enable it and get the link)

**Comment by bcpierce00** [comment]
Sounds good.

**Comment by bcpierce00** [comment]
Relabeled this as a design issue to be discussed after ICFP

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

I think the new UI probably resolved what this issue was discussing. Let me know if you think something is missing.
