### ISSUE TITLE
Get "security shield" working

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#122]
At the moment, the security shield messages go nowhere.  We need to either get text chat working a bit better (in particular, people with appropriate authority should be able to easily add people to this kind of semi-private channels) or else make the link to slack work again.

**Comment by bcpierce00** [comment]
What's our current plan for this, @jon-bell ?  (If both alternatives are equally easy at this point, I think the slack link may be more reliable for ICFP.)

**Comment by jon-bell** [comment]
I will set it up with slack next week

**Comment by jon-bell** [comment]
I just connected it to slack

**Comment by bcpierce00** [comment]
Great!!  

Do we want to keep the connection to slack long-term?  Or should we re-open this issue for later to remind us to pull it into Clowdr?

**Comment by jon-bell** [comment]
I am not sure what we want long term. Unless there are significantly better notifications in Clowdr, I assume people will continue to want slack.
