### ISSUE TITLE
"Author record" setting isn't getting saved

### ISSUE THREAD

**Issue by mikesperber** [clowdr-app/clowdr-web-app#123]
I'm a speaker at ICFP, and trying to link my Author record:

![image](https://user-images.githubusercontent.com/1387206/90146890-e4f4f580-dd81-11ea-96b6-3b0635063e02.png)

Unfortunately, clicking "Save" doesn't seem to save the settings: When I switch out of "My Account" and back, it's gone. Other changes (the home page, for example) are getting saved.

**Comment by bcpierce00** [comment]
This works for me, Mike.  Have you been able to get it to work?  If not, could you open the Javascript Console and see if there are any messages there that might be helpful when you click Save?

**Comment by mikesperber** [comment]
No, still broken. The console just has this:

`[DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input placeholder=​"input password" action=​"click" id=​"confirm" type=​"password" class=​"ant-input ant-input-sm">​`

**Comment by jon-bell** [comment]
Confirmed fixed (sudo'ed @mikesperber and successfully set his author record)
