### ISSUE TITLE
'Delete Channel' does not wait for confirmation dialog before deleting

### ISSUE THREAD

**Issue by jasonhemann** [clowdr-app/clowdr-web-app#124]
As I experience it

OSX, Chrome, in the Chat dialog and under "Other channels" the 'delete channel' option does not wait for confirmation before deleting the channel.

**Comment by bcpierce00** [comment]
Yes, there should be a confirmation dialog (and we should make this a "Moderators only" operation).

**Comment by jon-bell** [comment]
This is now fixed
