### ISSUE TITLE
Newly created rooms don't show the creator as a participant 

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#126]
(at least sometimes)

![image](https://user-images.githubusercontent.com/7014411/90150010-27530e00-dd53-11ea-9b4d-54e8cb9ebcf7.png)

**Comment by jon-bell** [comment]
The participants are stored as an array in Parse, which doesn't support atomic operations, so it is possible to race and remove/add end up with data loss. There is a more significant refactoring that needs to happen here to use a Parse.Relation instead.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
