### ISSUE TITLE
Event links go to blank pages when there's no room set up yet.

### ISSUE THREAD

**Issue by mcoblenz** [clowdr-app/clowdr-web-app#127]
If I click the link in the schedule for an event that is supposedly going on, it's possible for the event to have no room associated with it. The result is that the event link goes to a blank web page. This should at least result in an appropriate error message rather than a blank page.

**Comment by jon-bell** [comment]
FYI, this will not be implemented in time for ICFP - I think that our short-term fix is going to be to make sure that each event is assigned to a room.

**Comment by jon-bell** [comment]
I added an error so if you see it again you can blame the organizers and not me :)
