### ISSUE TITLE
Clowdr can't keep up with my typing

### ISSUE THREAD

**Issue by mcoblenz** [clowdr-app/clowdr-web-app#128]
I'm in a video chat room, and typing in the chat window is very laggy. Also, the video and audio are a bit flaky — I suspect the CPU demands are too high for my machine. I'm on a somewhat older machine (2013 MacBook Pro, 2.4 GHz dual-core i5).

**Comment by jon-bell** [comment]
What browser? How many people were in the video room?

**Comment by mcoblenz** [comment]
Safari 13.1.2. About 10 video members, 23 people in the text chat room.

**Comment by jon-bell** [comment]
Unfortunately there is literally nothing to do here other than cap the size of the room. I am not aware of *any* video chatting system that allows you to view that many simultaneous A/V streams in browser without taxing your CPU/GPU. Chrome might work a little better.

**Comment by mcoblenz** [comment]
Perhaps the video feature needs to move to a native app, then.

**Comment by mcoblenz** [comment]
Also, the chat is completely unusable. If it can’t be made usable with that many video streams, then cap the number of video streams (leaving audio streams instead).

**Comment by jon-bell** [comment]
@sweirich @bcpierce00 What do you want here?

**Comment by sweirich** [comment]
What is the number of people where things get troublesome?  Capping the size of the twilio rooms seems reasonable. We want them for small group discussions only.

**Comment by sweirich** [comment]
What happens when a room is "full"? What message do they get? Can they still access the chat?

**Comment by jon-bell** [comment]
I found the current capacity to be OK on my machine, but obviously this is not representative of all users. It would be very helpful if folks could test different capacities and report back when things start to degrade.

**Comment by jon-bell** [comment]
When a room is full they can't join it, and can not access the chat.

**Comment by mcoblenz** [comment]
Could it be set up so that any number of people could join a room, but the number of visible video streams would be throttled according to a user's HW limitations? Then all users would at least get audio, and we wouldn't have to limit everyone's video according to other people's hardware.

**Comment by jon-bell** [comment]
Yes, we should be able to provide a knob to allow you to determine how many video streams to receive concurrently. I'll try to get this in before ICFP starts.

**Comment by mcoblenz** [comment]
I don't mind helping test, but I recognize that my current machine is older and don't want to degrade everyone else's experience as a result.

**Comment by mcoblenz** [comment]
Awesome, thanks!

**Comment by jon-bell** [comment]
Solved -> we have lowered the room capacity
