### ISSUE TITLE
People with ICSE accounts having trouble logging in

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#129]
An ICFP participant (Kyeongmin Cho) is having the same trouble that I am still having on Chrome (not Safari), where something seems to remember the connection to ICSE and insist on going there.  I've tried clearing out my Chrome cache, to no effect.  Opening an incognito tab does work.

> I'm trying to sign in icfp2020.clowdr.org but it still forward me into icse2020 site without changing URL. Mysterious.. How can I join icfp2020 clowdr...?

**Comment by jon-bell** [comment]
I'm not sure what your trouble is that you are still having, but

**Comment by jon-bell** [comment]
@bcpierce00 can you follow up with this organizer to get them access? Are you sure that you added them to the ICFP registration list?

**Comment by bcpierce00** [comment]
Will do.

**Comment by bcpierce00** [comment]
This is not yet fixed for me, but if no one else reports it, then it's low-priority. Marking it Minor so we don't waste time on it.

**Comment by jon-bell** [comment]
@bcpierce00 do you have this issue when you visit https://icfp2020.clowdr.org ?

**Comment by bcpierce00** [comment]
In Chrome without incognito mode, yes.  Rechecked just now.
