### ISSUE TITLE
'People' list doesn't list self under 'Participants not in a room'

### ISSUE THREAD

**Issue by jasonhemann** [clowdr-app/clowdr-web-app#130]
I was trying to use this just to confirm where I was on the platform. I would have expected to see myself listed or perhaps the label "Other participants (not in a room)" instead.

**Comment by bcpierce00** [comment]
Jon fixed a bug today that might help with this.  Please comment here if you observe it again.

**Comment by bcpierce00** [comment]
This is still happening, @jon-bell 
![image](https://user-images.githubusercontent.com/7014411/90315205-98c3c580-dee7-11ea-8dd0-3bd40a1ba145.png)

**Comment by bcpierce00** [comment]
(Crista was also active then...)

**Comment by jon-bell** [comment]
I did not do anything to fix this yet

**Comment by bcpierce00** [comment]
This might have been fixed by Crista yesterday, but let's keep an eye out for it.

**Comment by jasonhemann** [comment]
I no longer face this issue.
