### ISSUE TITLE
AV options are not sticky

### ISSUE THREAD

**Issue by sweirich** [clowdr-app/clowdr-web-app#131]
Everytime I join a new ad hoc twilio video chat room my microphone/speaker/audio settings revert to the default settings. This is bad because the default doesn't work for me.

**Comment by jon-bell** [comment]
I'm going to lump this in with #3 as an issue that will require significant development in the Twilio end of things, and unfortunately won't be done in time for ICFP.

**Comment by sweirich** [comment]
That's unfortunate. This happens also whenever I refresh the window too. And it threw me for a loop whenever it happens because I wasn't aware that my audio wasn't working.

**Comment by sweirich** [comment]
I don't recall that this issue occurred at ICSE. Maybe my default audio settings just worked there? Not sure why they weren't working now.

**Comment by jon-bell** [comment]
It is unfortunate that we do not have more developers. This behavior hasn't changed since PLDI. I would suggest changing your OS' default audio settings, so that when Clowdr uses your OS defaults they will be what you hope they are.

**Comment by sweirich** [comment]
I will add this to the troubleshooting part of the Clowdr user manual.

**Comment by jon-bell** [comment]
I will close this and update #3 to include persisting the preferred input devices
