### ISSUE TITLE
Pin icon could be a bit larger

### ISSUE THREAD

**Issue by bgamari** [clowdr-app/clowdr-web-app#132]
In the "room" interface, the "pin" icon in the header of each participant's video stream is a bit small (and is smaller than the microphone icon). It would be helpful if it were a bit bigger and perhaps had a bit of horizontal whitespace to separate it from the the edge of the frame and the microphone icon as it's currently a pretty small target to hit.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(Video rooms were overhauled in the new UI)
