### ISSUE TITLE
Join by Zoom App doesn't work in VL/HCC Clowdr

### ISSUE THREAD

**Issue by mcoblenz** [clowdr-app/clowdr-web-app#133]
See attached screenshot. The "Join By Zoom App" button is disabled, and has been so for a couple of hours.

![image](https://user-images.githubusercontent.com/8899599/90152261-9fbace80-dd55-11ea-9df6-e6844e73683d.png)

**Comment by mcoblenz** [comment]
This is Safari 13.1.2.

**Comment by jon-bell** [comment]
Thanks for reporting this - I just fixed it (there was a configuration error in the zoom meeting)

**Comment by mcoblenz** [comment]
Thanks!
