### ISSUE TITLE
It is not obvious events have break-out rooms

### ISSUE THREAD

**Issue by bgamari** [clowdr-app/clowdr-web-app#134]
During our training session there were many events in the program which did not have an associated break-out room. However, this was not obvious from the entry in the "Program at a Glance" list in the left pane.

Two feature requests:

* the "program at a glance" entries with breakout rooms should have some sort of visual indication (e.g. a small icon) that the event has a breakout room
* when you click on an event without a breakout room, you are brought to the event page which describes the event, but there are no actions listed in the "actions" section (where one would usually find the "join breakout room" button). It would be better if there were some text explaining that there is no breakout room available (yet?) for the event.

**Comment by jon-bell** [comment]
Please follow the discussion in #121 for our current plans on breakout rooms.
