### ISSUE TITLE
Unable to scroll through chat messages

### ISSUE THREAD

**Issue by Quarkbeast** [clowdr-app/clowdr-web-app#135]
I am unable to scroll through messages in chats. This means I can only see that last few messages. This includes both the room specific blue chat and the general Lobby chat on the right. I am using Edge. But it also happens in Firefox (I know, not supported yet). Scrolling in other places (e.g. through the list of channels in the blue chat window) works fine.

**Comment by jon-bell** [comment]
Can you confirm if you see this behavior on Chrome or Safari?

**Comment by Quarkbeast** [comment]
I don't have either of those browsers installed at the moment. But I just found out there is a new version of edge which I am currently installing. I'll report back, whether the issue persists with an up to date version.

**Comment by Quarkbeast** [comment]
With the new version of edge the issue is gone.

**Comment by jon-bell** [comment]
Great! I do not have easy access to a windows machine right now, so testing what was going on in the old version might be a bit tricky, but in the future will be sure to recommend using an updated browser.

**Comment by Quarkbeast** [comment]
The update said that they changed the browser engine. That might be the reason.
