### ISSUE TITLE
SVs appearing offline

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr-web-app#139]
Some SVs are appearing as ‘offline’ i.e. they are not on the lobby list nor on People’s list. I know they are online because we were taking in a breakout room (and there their status was 'green'

**Comment by jon-bell** [comment]
I’m sorry it’s quite late here and I can’t get in to diagnose this right now - can you share (via private email to me might be better for PII) the SVs’ names that are currently appearing as offline, and tomorrow I will comb through logs?

**Comment by jon-bell** [comment]
I was able to deduce what was happening form the logs alone thankfully. This is now resolved and deployed.
