### ISSUE TITLE
[question]Private chat rooms still support up to 50 participants

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr-web-app#141]
Is this intended?

**Comment by bcpierce00** [comment]
Our decision to go down to max 4 might have been a bit hasty -- 4 feels a bit small even for informal chat, and some of the social activities may need more.  We can also use scheduled zoom rooms for social activities, but we should think a bit
 more carefully about what we want here.

**Comment by jon-bell** [comment]
I don't understand what the issue is here - would you please elaborate, @hannelita ?

**Comment by bcpierce00** [comment]
I think what she means is that 1-1 video rooms created from a text chat are still large rooms.  If so, I don't think this is a problem except that it makes them cost a bit more.

As an easy quick fix for the "four is too few sometimes" issue while we think about how we really want things to work, maybe we can bump the limit from 4 to 6?  Or is that nontrivial?

**Comment by EdNutting** [comment]
The new UI is set at max 10 for ordinary attendees and mods/admins get the choice to set the max (up to 50).
