### ISSUE TITLE
The video chat rooms are not deleted

### ISSUE THREAD

**Issue by ivg** [clowdr-app/clowdr-web-app#142]
To reproduce:

1. create a room
1. stay for some time in it
1. delete it by clicking on the red "Delete Room" button in the room widget
1. see the room staying

### Environment
Browser: Google Chrome 84.0.4147.125  (Official Build), used in the Incognito Mode
OS: macOS 10.11.6

### Additional Notes
An additional issue is that sometimes (can reproduce reliably) when I join the deleted room I am getting a misleading error message:

```
Error: unable to acquire camera
<snip>
Internal error message: TwilioError: Room not found
```

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
