### ISSUE TITLE
Rooms are duplicating

### ISSUE THREAD

**Issue by ivg** [clowdr-app/clowdr-web-app#143]
It happens sporadically, but I have experienced this twice in two different sessions. To reproduce:
1. Hit the "new video chat room" at the bottom left
2. Pick the name, leave everything else as default (ephemeral, public), and hit "Create and Join"

A few rooms will be created (I think they keep creating when I am creating other rooms). See icfp2020.clowdr.org for `test(ivg)` rooms. 

### Environment

Browser: Google Chrome 84.0.4147.125  (Official Build), used in the Incognito Mode
OS: macOS 10.11.6

**Comment by bcpierce00** [comment]
Thank you!  I think this is a display bug rather than a database bug.  If you refresh the browser, do you still see two rooms?

**Comment by ivg** [comment]
Yes, was just going to write this, if I reload (or relogin) then only one of the rooms is left, i.e., no duplicates. 

Another observation, this only happens on the first room I create, after logging in. The consecutive attempts are not creating duplicating rooms (though it looks like that they might re-duplicate the duplicated one).
