### ISSUE TITLE
Reports of no chat notifications

### ISSUE THREAD

**Issue by jon-bell** [clowdr-app/clowdr-web-app#144]
Report: 
>Several people messaged me to test the private msg mechanism and no badges appeared

**Comment by crista** [comment]
Needs reproduction

**Comment by crista** [comment]
I have a repro. This happens consistently on channels that haven't been visited before. For those, it takes 2 new messages for the count to be > 0, and then it's always off by 1. Once the channel is visited, the counts work correctly.
