### ISSUE TITLE
Feature request: a soundcheck room 

### ISSUE THREAD

**Issue by ivg** [clowdr-app/clowdr-web-app#145]
It would be nice to have a soundcheck room where a newly arrived user can check if his audio/video channels operate as expected. It could be a private room that is automatically created for each user (with appropriate tooling for the actual test, e.g., some sort of a bot that plays back audio/video).

As a workaround, just having a soundcheck room, where a student volunteer can greet people and tell them if they can hear and see the user as well as is the user microphone is loud enough and don't have any noises, echoes, and other artifacts.

**Comment by bcpierce00** [comment]
The more manual workaround is a good idea.  I wonder if we can use the "Information desk" for this.  (Indeed, I wonder if we should rename Information desk to Welcome Desk.)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, there is a pre-join screen for picking options and checking video/audio).
