### ISSUE TITLE
"Add person to text chat" button not working

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#149]
![image](https://user-images.githubusercontent.com/7014411/90315361-ef7dcf00-dee8-11ea-9ebd-6b703f98af03.png)

**Comment by pdonias** [comment]
Aren't these missing an argument? https://github.com/clowdr-app/clowdr-web-app/blob/836a252003306ffccc001145d9a5dba423da774c/src/components/Chat/MultiChatWindow.tsx#L136-L137

Should probably be:

```tsx
 toVideo={this.props.toVideo.bind(null, sid)} 
 addUser={this.props.addUser.bind(null, sid)} 
```

**Comment by crista** [comment]
yes, thanks!

**Comment by bcpierce00** [comment]
confirmed working now!  :-)
