### ISSUE TITLE
Unify the two different dialogs for creating video rooms

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#151]
If you create a video room from a text chat, you see this:
![image](https://user-images.githubusercontent.com/7014411/90317475-d92b3f80-def7-11ea-8986-1ff677e91395.png)
If you do it from the "Creat video chat" button, you get this:
![image](https://user-images.githubusercontent.com/7014411/90317490-f3651d80-def7-11ea-9e06-4a8a3ca00e2e.png)
Is there a good reason to have both?  Can we just use the second for everything?

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
