### ISSUE TITLE
Admin / Virtual Rooms upload should report errors

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#152]
At the moment, if anything goes wrong with a csv upload on the virtual rooms page (or other admin pages -- I think registrations has the same problem), no error message is printed -- it just silently fails.  This is... unhelpful.

**Comment by bcpierce00** [comment]
Moving this to the ICFP milestone.  Second time this week I'm helping Harry track down silent failures when he uploads his file...

**Comment by bcpierce00** [comment]
(but not high priority, obviously)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
