### ISSUE TITLE
Better styling for Program page

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#154]
The .css styling of the Program page needs some love.  In particular:

* There should be much less vertical space between items
* Everything should be top-aligned instead of some things top and some centered.

![image](https://user-images.githubusercontent.com/7014411/90333030-4ab6cc80-df90-11ea-935b-4372f25d409c.png)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
