### ISSUE TITLE
Search bar improvements

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#156]
- [x] The search bar is hard to find, and its positioning near the text chats suggests it can only be used to find chats.  Can we move it someplace more obvious -- e.g. the menu bar?
- [x] At the moment, the list of choices that pops up when you click in the search bar includes only chats. No way to tell that you can also use it to search for other things.

**Comment by jon-bell** [comment]
Changes for global search:
Before searching, just show a row that says "Search for papers, users, or chat channels"
When rendering the title for a chat that is with a person or about a paper, show the correct component that will give a tooltip
