### ISSUE TITLE
Long-running events can make the PaaG hard to navigate

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#160]
Design puzzle: Suppose a conference has one track with a single event that lasts all day and another track with 10-minute talks all day.  I believe the current semantics of Now will mean that the PaaG will be pinned to the beginning of the day, and the current talk in the second track will often be off the bottom of the screen.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
