### ISSUE TITLE
Add Lobby to list of text chats

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#161]
We've eliminated almost all of the session-level text chats, but there are still a number of places where the Lobby chat shows, and I think this is something we want to keep.  But it is then a bit confusing that people can't find it in the usual list of text chats.

Not critical for ICFP, if not easy.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
