### ISSUE TITLE
Video room creation fails

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#164]
When I tried to create a video room just now, the interface hung for a long time like this:
![image](https://user-images.githubusercontent.com/7014411/90433898-92c21600-e09a-11ea-87ff-badc04dca02d.png)
Then the console printed some interesting stuff...
![image](https://user-images.githubusercontent.com/7014411/90434104-dddc2900-e09a-11ea-8904-6c60e0e727c1.png)
![image](https://user-images.githubusercontent.com/7014411/90434126-e7659100-e09a-11ea-8338-839ea374a893.png)
(the last bit three times)

**Comment by jon-bell** [comment]
What revision of the code are you using?

**Comment by jon-bell** [comment]
I am not able to reproduce this on icfp2020.clowdr.org. I see that there was a request timeout for `/video/new` in the logs, but  nothing to indicate why. I added more logging, please let me know if you can reproduce it.

**Comment by bcpierce00** [comment]
unable to reproduce here too.  :-(

let's just keep an eye out for it.

**Comment by bcpierce00** [comment]
(that is, can't reproduce even on the new pr branch...)

**Comment by bcpierce00** [comment]
Let's close this issue for now.
