### ISSUE TITLE
Video chat names should also show up on the text channel picker 

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#165]
Right now it is not possible to focus the bottom window on the text channel for a video room.  I think it is natural to allow this.
![image](https://user-images.githubusercontent.com/7014411/90446481-77153a80-e0af-11ea-9444-e5a608d1373b.png)

**Comment by bcpierce00** [comment]
(Also room chat names, like Lobby and PLMW, as discussed on Slack.)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
