### ISSUE TITLE
Video room creation sometimes fails

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#168]
Clicking the Create And Join button again fails and adds another copy of the same message to the console log.  Reloading the page and trying again works.
![image](https://user-images.githubusercontent.com/7014411/90454152-6b7e3f80-e0c0-11ea-9388-12672d3f463e.png)

**Comment by bcpierce00** [comment]
Did you say you fixed this, @crista ?

**Comment by crista** [comment]
I did not work on this

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
