### ISSUE TITLE
"Search" interface results should include all events, not just main-conference papers

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#174]
Nuff said...

**Comment by jon-bell** [comment]
I believe that this is a configuration bug: Have you ticked the "chat" feature on any of the other tracks?

**Comment by bcpierce00** [comment]
Had not!  But clicking that button for the Haskell workshop doesn't seem to change anything...

**Comment by jon-bell** [comment]
Did you refresh your browser? I see all of the Haskell talks, and I just tested it with the OCaml one and it looks OK.

**Comment by bcpierce00** [comment]
thought I had, but... anyway, I see them in the search results now, but not the paper channel list.  is this intended?

**Comment by jon-bell** [comment]
This list currently only shows the paper channels that you have joined.

**Comment by bcpierce00** [comment]
ah, and visiting the paper talk or Q&A joins me?  that makes good sense.  if that's the design, then we are good for this one.

**Comment by jon-bell** [comment]
Yes, that is the design
