### ISSUE TITLE
icfp2020: Search doesn't show all expected results

### ISSUE THREAD

**Issue by turion** [clowdr-app/clowdr-web-app#176]
I tried to search for any tutorial sessions with the keywords "tutorial", "live" (as in "live coding"), "cubix". Nothing ever showed up.

**Comment by bcpierce00** [comment]
This will be fixed on the next refresh of the program.

**Comment by jon-bell** [comment]
(The issue is caused by a configuration of the conference tracks - not everything in the program has chat channels, for testing we have only a smaller subset of the program with chat channels)
