### ISSUE TITLE
Search bar is in a very unintuitive place, or rather, a real search bar is missing

### ISSUE THREAD

**Issue by turion** [clowdr-app/clowdr-web-app#177]
The search bar is in the lower left region, as opposed to somewhere on the top like in nearly every other web application.

Also, any results in the search bar only apply to the text chat, and not e.g. the program item. So in other words, a real search bar where one can search and enter program items is missing.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
