### ISSUE TITLE
Linux: Supply alternative forms of joining as host if xdg-open (or the browser's open dialog) don't launch zoom properly

### ISSUE THREAD

**Issue by turion** [clowdr-app/clowdr-web-app#178]
Today we tested for ICFP 2020 and found that in 3 cases with at least two different Linux distributions, the links "Join by zoom app" and "Join As Host" don't work. For "Join by zoom app" there is a workaround by pasting the link, such as https://us04web.zoom.us/j/12345678901?pwd=AAAAAAAABBBBBBBBCCCCC, into zoom and entering the password `AAAAAAAABBBBBBBBCCCCC`. But this does not work when joining as host. This is a problem.

There are possibly two solutions:

* Supply a "Join as Host by Browser" button. That would be great and painless.
* Someone else has to be present who is able to grant the host role to the intended host. Annoying workaround.

CC: @bgamari

**Comment by jon-bell** [comment]
> Supply a "Join as Host by Browser" button. That would be great and painless.
Unfortunately, I am not sure that this is easily attainable within Zoom's API. We're entirely removing the "join as host button" and will have a different approach for distributing the host privileges.

**Comment by bgamari** [comment]
I looked into the Zoom situation and am generally quite confused. From the `.desktop` file that is distributed with Zoom, it appears that opening a Zoom URL should launch a Zoom process with the URL as its first argument. However, doing this manually with the URL given by Clowdr did not appear to have any effect at all. Unfortunately, the Zoom executable also doesn't provide a `--help` flag, so it's hard to know how this is supposed to work.
