### ISSUE TITLE
The list of Users when adding to a chat room shows No Data initially

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#183]
The first time I click Add People and then click in the Users box, the list that pops up shows No Data.  If I start typing, the users appear, and if I bring up the dialog again it works fine.
![image](https://user-images.githubusercontent.com/7014411/90695693-e4a89e80-e248-11ea-9aa8-b41819db7922.png)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
