### ISSUE TITLE
Reaction emojis not working?

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#186]
Several people right now were having trouble adding reactions to chats, but the failure is intermittent.  :-(

The behavior is: Click on the reaction icon for a message, choose an emoji, nothing happens.  (Even after refresh.)  This happens for me about 30% of the time, with no pattern that I can figure out yet.

**Comment by bcpierce00** [comment]
Not sure.  Can you send me a couple messages so I can test?

**Comment by jon-bell** [comment]
I'm not sure what lets you reproduce this 30% of the time - I can't reproduce it at all. Please let me know if you find anything else that makes this easier to reproduce.

**Comment by crista** [comment]
It looks like it's another one of those "first time" behaviors. I can repro in the following way:
Login with 2 accounts. Go to any channel, possibly IM, between the two.
Send a message with one account.

- React with the other --> no show.

- React again --> it shows.

Repeat sending message. Same thing.

I'll try to fix it
