### ISSUE TITLE
URLs for chat rooms

### ISSUE THREAD

**Issue by asajeffrey** [clowdr-app/clowdr-web-app#187]
Currently there's no URLs for chat rooms, so there's no way to hyperlink to them. Instead of "Click here to chat with us!" you have "Find us in the chat picker at the bottom of the page".

**Comment by asajeffrey** [comment]
Something like a query parameter to the clowdr URLs that selects which chat room to show at the bottom of the page would do the trick.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(The new UI uses unique URLs for each chat/video room as part of our "open stuff in multiple tabs" design philosophy).
