### ISSUE TITLE
Remove video chat list from LH sidebar?

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#190]
Stephanie and I wonder whether it might be conceptually and visually simpler to just delete the Video Chat Rooms bit of the left sidebar and let people get to these rooms via the People/Places page...

**Comment by bcpierce00** [comment]
(a) It will not completely remove this ability -- you just have to open another tab onto People/Places.

(b) The current design is not quite the right thing either:
   -  If there are a lot of rooms or a lot of people in rooms, it will eat into the space for the PaaG
   - it doesn't belong with the program (semantically, it would make more sense on the right)

(c) I'm still concerned about how busy / complex the overall interface is.

**Comment by crista** [comment]
+1 for removing the video chat list from the left side bar for now.
We need to simplify the UI... after ICFP

**Comment by bcpierce00** [comment]
I will remove it for now

**Comment by bcpierce00** [comment]
I think I like this, Crista.  IMO, two big things it’s missing are (a) some way of watching multiple channels at once, and (b) a really good story about multiple browser windows.

Best,

     - Benjamin

**Comment by EdNutting** [comment]
Funny, I was just showing Benjamin and Harry a prototype that is a similar idea of simplifying to a Slack/Discord style UI. The initial work is in my branch `ui-overhaul` in my fork. We should discuss this on Sunday when you've got time?

**Comment by EdNutting** [comment]
Early work but you can see the basic idea. The sidebar collapses uses the burger button top-left. Various of us were discussing on a video room on ICFP Clowdr ideas for UX/UI - I'll allocate time on Sunday to log them on this ticket.

![image](https://user-images.githubusercontent.com/1746336/91590963-12ca6480-e954-11ea-9b35-ce074d600ef8.png)

**Comment by crista** [comment]
Yes, let's discuss this! But we need to include @bcpierce00 and @jon-bell. Let's coordinate in Slack.
