### ISSUE TITLE
Joining a text channel doesn't always work

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#196]
Steps:

* Hover over Mentoring channel and click Leave
* Search for it in the search bar at the top; type Return
* Observe that it is now subscribed again, but it has not appeared in the center pane

![image](https://user-images.githubusercontent.com/7014411/90844388-c4084380-e331-11ea-9955-eab6102f075c.png)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
