### ISSUE TITLE
Insufficient bandwidth warnings not properly placed

### ISSUE THREAD

**Issue by psybers** [clowdr-app/clowdr-web-app#2]
When there are bandwidth issues, an 'insufficient bandwidth' warning draws over the grey'd out video stream(s). However that warning is not properly sized/placed and overlaps the chat window and other streams that are not grey.

Example 1:
![image](https://user-images.githubusercontent.com/1115390/84539414-57cdeb80-acc1-11ea-94d1-ec695590cc41.png)

Example 2:
![image](https://user-images.githubusercontent.com/1115390/84539426-5ac8dc00-acc1-11ea-921c-0787674a2b5f.png)

**Comment by jon-bell** [comment]
Thanks! We've solved this.
