### ISSUE TITLE
Make links for joining Live Now events available 2 min before

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr-web-app#200]
It is very likely people will try to join 1 or 2 min before, especially for the Q&A. SVs also need to share the right link for Q&A in the ongoing chat ~2min before, so they need to easily get the right link that sends participants to the "Join Zoom". Ideally on the left bar, we should get the link 2 min before \cc bcpierce00

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, Join Zoom buttons appear 20 mins prior to the session start).
