### ISSUE TITLE
Periodically refresh user display names, profile text, etc.

### ISSUE THREAD

**Issue by mattmccutchen** [clowdr-app/clowdr-web-app#203]
On the ICFP 2020 Clowdr site, I've been told that my name appears as "Matt McCutchen" to some users and "Richard McCutchen" to others.  I want to use "Matt McCutchen" and have entered that name form on the Account tab.  I also go by "Richard McCutchen", but I don't know how that name got into Clowdr.

If this issue should be filed somewhere else, please let me know.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
