### ISSUE TITLE
Lower right chat panel sometimes jumps to a different session channel without updating the title

### ISSUE THREAD

**Issue by mattmccutchen** [clowdr-app/clowdr-web-app#204]
While participating in the ICFP 2020 Clowdr training session a few hours ago, I observed the following behavior:

1. I selected my paper from the Program at a Glance, and the paper chat channel loaded in the lower right panel as expected.
2. Another user commented in the "ICFP Social" chat channel, and the lower right panel switched to showing the _content_ of the "ICFP Social" channel, while the _title_ of that panel continued to show the title of my paper.  I would expect the title to update or the panel not to switch at all.

I don't know the exact conditions under which this reproduces.  Please let me know if I should report this somewhere else or I can assist with investigation.

Not automatically switching the lower right panel makes more sense to me, but if the switching is an intended feature and someone can tell me the conditions under which it occurs, I will document it in the user manual; then this issue will be to fix the incorrect title.

**Comment by bcpierce00** [comment]
Is this better now?

**Comment by mattmccutchen** [comment]
Indeed, I don't remember seeing the problem since Sunday.  I'll reopen if I see it again.
