### ISSUE TITLE
RAM spikes

### ISSUE THREAD

**Issue by laMudri** [clowdr-app/clowdr-web-app#209]
I'm not sure what else this affects, but I noticed yesterday that navigating to the Student Research Competition gallery page required, at its peak, over 2 GiB of RAM. This meant that when I was trying to follow along with Benjamin's tutorial, my computer started swapping aggressively and I missed the entire rest of that tutorial.

System:

```
Chromium 84.0.4147.125
Linux 5.4.53 x86_64
```

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(Though we're aware of various similar performance problems in the new UI that we're working to resolve).
