### ISSUE TITLE
Conserve screen real estate in the right-hand sidebar

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#210]
The contextual chats may go by quickly in a large session and thus be hard to keep track of.

Two ideas:

* [ ] Allow people to minimize the list of users in the room (by putting a close/open thing on the side, similar to the "X total" thing currently on the bottom right of the list of users in the current space).
* [x] Either display the message time on the same line as the sender, or else (better, I think) omit it entirely and only display it when you hover over the message.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
