### ISSUE TITLE
Emoji button hovers over the text

### ISSUE THREAD

**Issue by ulysses4ever** [clowdr-app/clowdr-web-app#211]
At first I thought it’s no big deal. But after using the chat for some time I found this quite annoying.

![50C3C8D3-2543-47AC-A95D-A4EB250571B6](https://user-images.githubusercontent.com/6832600/90963307-810ab500-e484-11ea-8fed-e38bd6827ff1.jpeg)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
