### ISSUE TITLE
User homepage URL can be interpreted relatively

### ISSUE THREAD

**Issue by dunnl** [clowdr-app/clowdr-web-app#214]
As I'm browsing user profiles, the URLs to people's homepages are sometimes relative (e.g., at ICFP, clicking the hyperlink takes me to `https://icfp2020.clowdr.org/live/now/<user's URL>`, which makes no sense). The pattern seems to be that the user must explicitly include the scheme `https://` or `http://` to avoid this behavior. I think there is never a situation when this makes sense, and the URLs should always be interpreted absolutely.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(This was also a duplicate and has been resolved in the new UI)
