### ISSUE TITLE
New message notifications sometimes appear even though the channel is displayed in the RH sidebar

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#216]
E.g., check out what's happening with Lobby here:

![image](https://user-images.githubusercontent.com/7014411/90980089-32fabd80-e527-11ea-856f-4af9e8727cb2.png)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
