### ISSUE TITLE
Chat sometimes swallows messages.

### ISSUE THREAD

**Issue by hgoldstein95** [clowdr-app/clowdr-web-app#217]
I've seen this 3 or 4 times now. It seems to happen when multiple people are chatting at once, so it might be a race condition?

**Comment by mattmccutchen** [comment]
I've seen this several times.  I'm trying to remember to copy each message to the clipboard before I send it.

**Comment by bcpierce00** [comment]
We believe this will be fixed when we redeploy the system after today's events finish.  Please let us know if you notice any more misbehavior tomorrow.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(For the new UI, we've had no reports of anything like this during CSCW nor seen it during testing, so I'm assuming it's not an issue).
