### ISSUE TITLE
User's name not showing in the text chat

### ISSUE THREAD

**Issue by sweirich** [clowdr-app/clowdr-web-app#218]
Ran into a strange issue with user names not displaying correctly in text channels. 

I added a second account for a user that mistyped his email in regmaster.  Now his posts look funny in the chat. See screenshot.

![Image 8-23-20 at 9 58 AM](https://user-images.githubusercontent.com/2103670/90980080-28402880-e527-11ea-9e68-f1df78fe5f7b.jpg)

Harry says refreshing helps.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
