### ISSUE TITLE
See All Messages feature

### ISSUE THREAD

**Issue by dunnl** [clowdr-app/clowdr-web-app#221]
**Feature request:** To see all direct messages I was sent by any user (or something similar).

Background: I accidentally left a DM channel that was opened when a user sent me a message. After it was closed, I could not find a way to determine which user sent me the message, and therefore I could not open the channel to see the message. Only when I happened to recognize the user's name could I re-open the channel by clicking the user's name.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, there is a Recent Messages list. We'll also be adding an "unread messages boldification" soon).
