### ISSUE TITLE
Create a dummy backend instance so it's easier to test frontend locally

### ISSUE THREAD

**Issue by ulysses4ever** [clowdr-app/clowdr-web-app#222]
Having a dummy backend with a publicly available `.env` would lower the entry barrier to crowd-sourcing improvements to the frontend.

**Comment by bcpierce00** [comment]
That would be great.

**Comment by EdNutting** [comment]
Closing as the new UI/backend has been developed after this issue was opened and this issue relates only to the old system. 

In the new system, we are able to do entirely local development (-Twilio/Sendgrid) using Parse locally + Ngrok to route Twilio callbacks.
