### ISSUE TITLE
New message notifications are inconsistent across multiple browser tabs

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#224]
E.g., see the "PLMW" notifications here:

![image](https://user-images.githubusercontent.com/7014411/90982836-0a2ef400-e538-11ea-8f32-24bb367af20a.png)

**Comment by hannelita** [comment]
[SUGGESTION] @bcpierce00 One suggestion, that IDK if it's possible, is maybe using a protocol, like XMPP, for dealing will all the chat and rooms. I understand that we use Twilio now, but maybe (Maybe!) it would make sense to create a more robust mechanism for chat messages; XMPP could (in theory) also wrap the video rooms in some sense, leaving all the Communication layer managed by one uniform protocol

**Comment by jon-bell** [comment]
FWIW, Twilio's chat API supports syncing notifications across clients

**Comment by EdNutting** [comment]
Twilio is a very robust and popular platform. Changing protocol, building a chat backend, and everything else involved in making it scale would be an insane amount of work. From the code review Harry and I did, it's just Clowdr's use of Twilio that needs refining (message notifications are computed locally in the tab afaict so yeah, it's not surprising that goes out of sync).

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(The new UI does not have unread counts yet - but they're coming).
