### ISSUE TITLE
The "delete message" button doesn't (always?) work

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#232]
E.g.: Click the red X to delete a partial message
![image](https://user-images.githubusercontent.com/7014411/91066894-3dd55100-e600-11ea-9be8-df7b02e99569.png)
... and observe that it is still there (even after a refresh)
![image](https://user-images.githubusercontent.com/7014411/91066953-50e82100-e600-11ea-9db7-b234d6320709.png)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
