### ISSUE TITLE
Contextual chat doesn't work if there is a simultaneous Q&A session

### ISSUE THREAD

**Issue by turion** [clowdr-app/clowdr-web-app#233]
I'm currently watching the video to https://icfp2020.clowdr.org/program/f4CrvfGR2U/zypae6LTvf through clowdr. As you can see in the screenshot, the contextual chat is wrong. It's the chat to a Q&A session which happens to be simultaneous.

![image](https://user-images.githubusercontent.com/303489/91068863-295f7b80-e635-11ea-9e3c-ea37c2d64278.png)

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
