### ISSUE TITLE
Favourite talks with reminders or automatic video start

### ISSUE THREAD

**Issue by turion** [clowdr-app/clowdr-web-app#234]
I noticed that I keep missing interesting talks I wanted to go to because there is no equivalent of conference organisers announcing the start of the next session in the coffee room.

It would be great if one could mark talks as favourites ahead of time, and be reminded when they start. Alternatively, a favourite talk could start automatically.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, we implemented a "Followed Items" feature that enables exactly this, among other things.)
