### ISSUE TITLE
Subprogram items are not sorted by time

### ISSUE THREAD

**Issue by bcardiff** [clowdr-app/clowdr-web-app#237]
In the program section, the subprogram items are not sorted by time.

For example, in the entry for `Tue 24 Aug | 12:30 PM - 2:00 PM | ICFP Program: New York 3 (JFP talks)`

The first items are

* Perturbation confusion in forward automatic differentiation of higher-order functions (Tomorrow at 1:26 PM)
* Heterogeneous binary random-access lists (Tomorrow at 1:03 PM)
* Local algebraic effect theories (Tomorrow at 12:52 PM)
* etc.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
