### ISSUE TITLE
Allow direct links from the program to external URLs

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#239]
in ProgramSessionEventDIsplay, if `linkTo` starts with http, then instead of showing a <NavLink>  it should do a regular `<a href=…>`

**Comment by caasi** [comment]
bump for this feature

<img width="759" alt="截圖 2020-08-25 下午11 12 40" src="https://user-images.githubusercontent.com/1164470/91192825-fc8c9080-e728-11ea-90b1-beaf41e876ff.png">

**Comment by EdNutting** [comment]
Does this refer to `ProgramItemDisplay` or to `ProgramSessionEventDisplay`? In `ProgramSessionEventDisplay` there appears to be a `directLink` field which would resolve this. `ProgramItemDisplay` lacks the equivalent feature.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(I think in the new UI this was resolved using attachments &/ markdown)
