### ISSUE TITLE
Admin crash on Registration

### ISSUE THREAD

**Issue by crista** [clowdr-app/clowdr-web-app#241]
Got this when filtering registrations by date.

![image](https://user-images.githubusercontent.com/109621/91226015-48174e00-e6d9-11ea-900d-be238063025a.png)

**Comment by EdNutting** [comment]
Hmm, unfortunately that error trace doesn't show which component in the Admin Registration caused it. 

I tried to reproduce this but no longer get an error. Recent cleanup may have fixed but it'd be good to repro on an earlier version then bisect.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
