### ISSUE TITLE
Make it harder to accidentally leave a video call

### ISSUE THREAD

**Issue by Lysxia** [clowdr-app/clowdr-web-app#242]
Right now you leave the call as soon as you move to another location. You can mitigate this by having multiple tabs, but I still got confused several times. It would be nice to have a warning to confirm whether you want to leave the call.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, such warnings have been implemented.)
