### ISSUE TITLE
Setup instructions: MongoDB no longer includes mongorestore

### ISSUE THREAD

**Issue by EdNutting** [clowdr-app/clowdr-web-app#243]
As per documentation on this page:

https://docs.mongodb.com/database-tools/mongorestore/#installation

mongorestore is now part of MongoDB Database Tools, which are not included with MongoDB Server. This should be reflected in the main ReadMe.

**Comment by bcpierce00** [comment]
Please feel free to fix the instructions!

**Comment by EdNutting** [comment]
Will do - this is partly logged as a mental note while I figure out how to get this set up / working! :)
