### ISSUE TITLE
Creating a new room should be possible without joining

### ISSUE THREAD

**Issue by hgoldstein95** [clowdr-app/clowdr-web-app#248]
Currently when creating a new video room, the only way to submit the form is "Create and Join". I propose that it be changed to "Create". This is better for a few reasons.

* Joining a meeting is currently not possible with no camera, but that shouldn't make it impossible to create a room.
* The default for joining a room is camera on, so that might make people uncomfortable creating a room.
* If making multiple rooms at once, "Create and Join" is slow and frustrating.

In fairness, fixing the fact that (1) a camera is required to join a room, and (2) the default is camera-on would make this issue much less important, but it still seems like an obvious UX improvement.

**Comment by bcpierce00** [comment]
Agreed!

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
