### ISSUE TITLE
Occasional difficulty returning to chat room from e.g. private chat

### ISSUE THREAD

**Issue by jasonhemann** [clowdr-app/clowdr-web-app#250]
I run into an occasional issue if I 

1. Enter a session room
1. Move to a DM text channel
1. Attempt to return to that same session channel. 

In this case, sometimes, I have had trouble re-entering the chat room (the one in the center of the screen.) 

The current work around is to click on another chat room, enter that, and then re-enter the chat room I was looking to get to.

**Comment by EdNutting** [comment]
Our recent work cleaning up the code cleared a few hidden Chat-window update issues. We will need to repro on an earlier version and bisect to see if we fixed this already (or not...which is just as likely at this stage).

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
