### ISSUE TITLE
Embedding videos attached to Program Items

### ISSUE THREAD

**Issue by pained** [clowdr-app/clowdr-web-app#266]
It would be helpful to add a feature to the UI to take a Media Attachment Link and render an embedded video when appropriate.

Example:
CSCW2020 is having author's pre-record all videos and they will be uploaded to YouTube. We want to provide the YouTube link and have an embedded player display on a Program Item's page. That way an attendee does not have to leave Clowdr to watch this video.

**Comment by EdNutting** [comment]
I will include this as part of the new UI development. As per our offline discussion, these can be included as a content feed against the program item ("Program Room" in the old UI parlance).

The new UI will enable 3 ways to attach YouTube/Zoom/Breakout Room (Twilio) aka Content Feeds to Program features:

1. A feed for a `Program Session` (A group of events)
1. A feed for a `Program Session Event` (E.g. a paper, demo or workshop)
1. A feed for a `Program Item` (Each `Program Session Event` has an `Item`; `Item`s can also be selected separately to be displayed as posters/exhibits.)

Note that, iirc, if an `Item` is not assigned any `Event`s nor selected to be exhibited, then it essentially becomes invisible - there won't be a way for people to find it. So all items need to either be part of an event or selected for exhibition. Please let me know if I've missed a use-case.

For the CSV, for now, please feel free to use a format that makes sense/makes this easy for you to encode. So long as it's consistent and I know what columns provide what data, then I can automatically process it into the new UI.

**Comment by pained** [comment]
Yes that aligns with what was discussed yesterday I believe. I keep coming back to the terminology being a bit convoluted with things like papers being referred to as "events", and this it outside this issue's scope somewhat, but I guess I see these two key things:

1.  Sessions -> groups of program items (papers, posters, demos, keynotes, workshops) happening in a set timeframe & room
2. Program Items -> the above types of things with attributes including: item name, authors, abstract/text, links, track, session name

I may be oversimplifying however.

**Comment by EdNutting** [comment]
This may help others who come across this:

* Items are posters, papers, etc - the artifacts submitted to a conference. These have authors.
* Events are scheduled times for items to be presented (maybe multiple events for one item e.g. a paper presented in two timezones)
* Sessions are groups of events.
* Tracks are groups of sessions and items (for items that aren't scheduled like exhibited posters).
* "Rooms" are sources of content - Zoom, YouTube, etc (I am renaming these to Content Feeds in the redevelopment work)

Sessions, events and items can all have Content Feeds (aka Rooms) - i.e. they can all source a stream from Zoom, YouTube, etc. Content Feeds are mandatory for Sessions, and optional for Items and Events. In practice, it is normal for a Session's Content Feed (e.g. a YouTube livestream) to be where a series of talks are delivered. Events may have additional content (such as Q&A) supplied through their feed. An Item's feed might, for example, be used for unscheduled items (e.g. poster presentations pre-recorded on YouTube) or for providing a space to discuss the item outside of scheduled time.


So for example:

* Tracks: Keynotes, Research Papers, Demos, Posters
* Items: "Lorem Ipsum Paper 1", "It's all Greek to me Paper 2", "I thought it was French Paper 3"... "My Awesome Poster 1", "That project some student submitted late Poster 2", etc
* Events: "Paper 1 - EST Timezone", "Paper 1 - CST Timezone", "Keynote 1 - EST Timezone"...
* Sessions: "Keynote Day 1", "Research Papers Day 1"
* Rooms: Various content feeds for the different sessions (from YouTube/Zoom/etc)

For larger conferences with co-hosted workshops:

* Tracks: ICFP, PLMW, HIW, TyDe, OCaml, Scheme
* Items: All the papers, demo, posters, etc
* Sessions: The various grouped periods of presentations and social time within each track (often e.g. "Name Of Track: Session 1"). These were often duplicated, one session for each timezone.
* Events: The times that specific items (papers) were being presented.
* Rooms: The various YouTube livestreams for each session, some Zoom rooms for Q&As for specific events (when authors were available). [Items did not have feeds - this was later requested by organisers.]

**Comment by EdNutting** [comment]
Original request was completed.
