### ISSUE TITLE
Registration Screen Not Scrolling in Firefox on Mac

### ISSUE THREAD

**Issue by potanin** [clowdr-app/clowdr-web-app#270]
When I do my registration in Firefox on Mac, I have to resize the window to get to "Register" button as scrolling does not work. This can be due to my 4-5 Firefox plugins including Zoom though. Screenshots attached.
![Screen Shot 2020-11-05 at 11 00 28 AM](https://user-images.githubusercontent.com/2880662/98172585-7d041480-1f56-11eb-816d-c89536feedca.png)
![Screen Shot 2020-11-05 at 11 00 35 AM](https://user-images.githubusercontent.com/2880662/98172611-82f9f580-1f56-11eb-81c7-6e67cf8304fe.png)

**Comment by EdNutting** [comment]
Okay I'll try to reproduce on Windows.

**Comment by EdNutting** [comment]
Fix has been deployed for SPLASH from my branch and will hit upstream in future.
