### ISSUE TITLE
Changing channels shouldn't un-mute audio/video

### ISSUE THREAD

**Issue by psybers** [clowdr-app/clowdr-web-app#3]
Steps to reproduce:

1) mute audio (and/or video)
2) change to another channel

expected behavior:
audio/video is still muted/unmuted, similar to the state in the previous channel

observed behavior:
audio and video are always unmuted

**Comment by Chobbes** [comment]
Seems to still be an issue in the ICFP version.

**Comment by jon-bell** [comment]
This is not on my milestone for ICFP, and I definitely do not have bandwidth to implement this by then, sorry. I am happy to point you to where in the code to get started with this though.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(The new UI has a pre-join screen that remembers previous settings)
