### ISSUE TITLE
No scroll bar in Firefox

### ISSUE THREAD

**Issue by Inventitech** [clowdr-app/clowdr-web-app#36]
I know Firefox is not currently supported, but it actually works great with the exception of one relatively major feature: 

Using Firefox 77.0.1, there are no scroll bars in chat windows. This concerns the small 'Facebook-style' pop-up chat windows as well as the big, right-column chat bar. Even in the absence of scroll bars, scrolling in these regions is impossible. I cannot use my mouse or do the old trick of marking text and dragging it. 

There **are** scroll bars in the left "status" bar column, so I am hoping this would be an easy fix. 

Thanks for looking into this once you find time. It is not urgent for me.
![Screenshot from 2020-07-09 12-06-27](https://user-images.githubusercontent.com/334256/87027113-f96f2c80-c1dc-11ea-90aa-c3f60ec488e1.png)

**Comment by EdNutting** [comment]
Related issues (covers both Edge and FF):
https://bugzilla.mozilla.org/show_bug.cgi?id=1042151
https://github.com/philipwalton/flexbugs/issues/108

**Comment by EdNutting** [comment]
According to that first Mozilla bug, the fix for this has landed in FF81 in literally the last 19 days and will reach users from 2020-09-22 (see [Release schedule](https://wiki.mozilla.org/Release_Management/Calendar)). My recommendation therefore is not to adjust the existing code and wait to see if the patch to FF resolves this for us.

**Comment by EdNutting** [comment]
Just installed the FF81 beta `81.0b2 (64-bit)` and can confirm it has fixed the issue, so definitely best to just wait. Also validated the fix against ICFP.

**Comment by crista** [comment]
yoo-hoo!

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
