### ISSUE TITLE
Claiming authorship

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#42]
Need to add the ability for users to claim authorship of papers/posters, so that they will automatically join the chat 
associated with their work, and see notifications when people comment on it or ask questions

The posters/demos chairs should have a special role that allows them to associate "ownership" of the posters to specific email addresses. From then on, the users with those email addresses will have write permissions on the posters. (This is one-off procedure  for ICSE that should be generalized later for future conferences: track chairs should have special roles that allows them to set things up)

**Comment by jon-bell** [comment]
Current status: Users can now choose their own authorship. If this is OK, we can close this for now.

**Comment by bcpierce00** [comment]
IMO this is fine for the moment.
