### ISSUE TITLE
"Self-driving" mode for set-up and adminstration

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#43]
Make it possible for people to set up and use Clowdr without devs in the loop.

* [ ] Admin manual / README
* [ ] Set up a demo site that we can show people

**Comment by bcpierce00** [comment]
This isn't finished, of course, but we're making progress on both items.  No need for Urgent any more.

**Comment by EdNutting** [comment]
We're working towards getting this back in the new UI. Closing this issue in favour of tracking in newer ones (inc. some of our internal ones)
