### ISSUE TITLE
Program / Researchr-like features

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#51]
Either integrate our Program with Researchr (especially including "My Program" view) or else
  duplicate that functionality in the Clowdr Program tab

(We decided the
  latter was more plausible short-term, but the former would be a better
  incentive for the researchr team to collaborate with us!)

**Comment by jon-bell** [comment]
Is the starr'ing on program items that I added sufficient?

**Comment by bcpierce00** [comment]
I'd still like to see some kind of integration of starring with the Program at a Glance.  (I.e., I want to be able to restrict my view to just things I've starred.)  But this can wait for after ICFP.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
