### ISSUE TITLE
Deleting a room should make its text chat window go away

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#52]
- [x] allow editing posts on chats
- [ ] deleting a room should make its text chat window go away
- [x] make chat windows resizeable (and reconsider how they are laid out -- e.g., should they be on the bottom of the screen, or should they share space in the right-hand sidebar?)

**Comment by jon-bell** [comment]
FYI, it was always possible (from day 1 of chat) to edit your own chat messages, and for moderators to edit any.

**Comment by bcpierce00** [comment]
I'll open a fresh issue for the bit of this that's not done yet
