### ISSUE TITLE
Simplify closing vs. minimizing of text chat windows

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#56]
To minimize confusion about closing the text chat windows, what about
     removing the X from the chat window itself and making the -- (minimize) do
     what the X does now?  I.e., the only way to really close a chat window is
     from the sidebar?

**Comment by crista** [comment]
Related to #52

**Comment by bcpierce00** [comment]
No longer relevant since Jon's recent text chat changes.
