### ISSUE TITLE
Highlight active posters

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#57]
Consider how to make it clear which poster sessions are active at the moment (add a list to the Posters page, maybe? and/or to the Lobby page?)

**Comment by jon-bell** [comment]
I've added the posters to the lobby (specifically: for each track that has breakout rooms, it will show the breakout rooms organized by the track along with who is in them) - I think that this might be sufficient now?

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
