### ISSUE TITLE
Feature: Allow muting by default on rooms

### ISSUE THREAD

**Issue by anka-213** [clowdr-app/clowdr-web-app#6]
When people join to listen, they will have the audio on by default and may accidentally cause a bunch of noise to people around them. It would be useful to set a room to mute by default so everyone who joins won't have to explicitly mute and disable video.

**Comment by jon-bell** [comment]
Thanks! We've solved this in 81bff270df7ad310b98d66379b76f9c84f4408e3

**Comment by anka-213** [comment]
Sweet! That was a really quick response! ❤️
