### ISSUE TITLE
Emoji nits

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#66]
- [ ] Add Emoji reacts for talks (thumbs up, clap, heart). Send as JSON messages in Twilio. 
- [x] Emoji renderer should never show "undefined" (try typing e.g. :shrug:)

**Comment by bcpierce00** [comment]
I think this is done now?

**Comment by jon-bell** [comment]
The first part still needs to be done, the second is done (and you get 👍 too)

**Comment by jon-bell** [comment]
Emoji reactions are completed, and there's also now an emoji picker for text entry
