### ISSUE TITLE
status colors and text are not getting updated when they change

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#80]
... on the ISSTA site, at least

**Comment by jon-bell** [comment]
Can you confirm if it is not updating, or if it is updating, but with a 10-15 second delay? It is currently intentional that the update is not immediate across the network (to reduce flooding and UI redraws), but agreed that the local UI should reflect *your own* changes without delay.

**Comment by bcpierce00** [comment]
not updating

<img width="594" alt="image" src="https://user-images.githubusercontent.com/7014411/87963887-6f9a4b80-ca87-11ea-9543-d2d69b5faf32.png">

**Comment by jon-bell** [comment]
How long did you wait between the update and the screenshot?

**Comment by bcpierce00** [comment]
40 min?

**Comment by jon-bell** [comment]
Something was weird with your UserPresence object, likely due to it being created with an older version of clowdr. I just fixed it in the DB, and it should now work. I also made it so that your own presence will update immediately in your own UI, rather than with the delay.

**Comment by bcpierce00** [comment]
works!
