### ISSUE TITLE
Support DM'ing users who have not yet signed up

### ISSUE THREAD

**Issue by jon-bell** [clowdr-app/clowdr-web-app#83]

**Comment by bcpierce00** [comment]
Still relevant?

**Comment by jon-bell** [comment]
Yes, but probably extremely low on the priority list

**Comment by EdNutting** [comment]
Does this even make sense in the new system?

**Comment by jon-bell** [comment]
The problem was that we didn’t create the Twilio user until after the user logged in the first time (rather than when they were registered). If the twilio users get made right away now, then it should be all good now.

**Comment by EdNutting** [comment]
Ah okay, then yes I resolved this.
