### ISSUE TITLE
Slightly more informative message for Firefox users

### ISSUE THREAD

**Issue by potanin** [clowdr-app/clowdr-web-app#89]
Hello,

As JB said:

"Yup, we had a discussion with Alan Jeffrey at Mozilla about this. Their WebRTC implementation was the first implementation out there… and before the standard was finalized. As a result, Firefox does not have as stable of support for WebRTC than other browsers. If you are in a twilio-based video room and there are more than 2-3 video streams, your CPU will spike to 100% and it will get very choppy."

It may be better to display this kind of explanation rather than just say that Chrome/Edge/Safari only are supported as there are a lot of Mozilla supporters/sponsors using Clowdr.

I'll see if I find time to edit the alert myself using this issue for PR. :)

Cheers,
Alex.

**Comment by jon-bell** [comment]
FWIW, the level of bad for FF so far has been that people were joining video calls in FF anyway, and having a terrible experience and moving to Chrome or Safari, so it might be best for us to not show this warning, and instead prevent you from joining a video room altogether if you are in FF (and show a message to that effect).

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(FWIW, the new UI supports Firefox better than Chrome at the moment haha. We're working to level it all out).
