### ISSUE TITLE
Delete users via admin interface

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#90]
A “delete” button on the user admin page would be handy. Deleting a user should:
Dissasociate any existing ProgramPersons from that UserProfile
Remove the UserProfile from that Users’s list of profiles
Delete the UserProfile

**Comment by bcpierce00** [comment]
This is high priority for giving organizers an admin interface that is sufficient to manage the conference without fiddling with the parse database.  But For ICFP we can get away with database fiddling.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(This was implemented as "Ban User" in the new UI)
