### ISSUE TITLE
Make the "Send" button in Admin/Registrations more eye-catching

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#91]
When a new registration is entered by hand, it's easy to forget to press the Send button.  To make it more obvious, the the buttons in the Invitation column should be colored red when their text is "Send" (not when it is Re-send).

Also, by the way, there's a redisplay bug in this code: The button text does not change to Re-send until the page is refreshed.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
